package com.example.emre.examplephonelist;

import android.graphics.Point;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.DisplayMetrics;
import android.view.Display;
import android.widget.ExpandableListView;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class MainActivity extends AppCompatActivity
{

    private ExpandableListView listView;
    private ExpandableListAdapter listAdapter;
    private List<String> listDataHeader;
    private HashMap<String, List<String>> listHash;


    @Override
    protected void onCreate(Bundle savedInstanceState)

    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
;
    listView = findViewById(R.id.lvExpand);
    initData();
    listAdapter = new ExpandableListAdapter(this, listDataHeader, listHash);
    listView.setAdapter(listAdapter);
        Display display = getWindow().getWindowManager().getDefaultDisplay();
        DisplayMetrics point = new DisplayMetrics();
        display.getMetrics(point);
    listView.setIndicatorBounds(point.widthPixels - 100,point.widthPixels);
    }

    private void initData()
    {
        listDataHeader = new ArrayList<>();
        listHash = new HashMap<>();

        listDataHeader.add("LOCO USERS");
        listDataHeader.add("INVITE TO LOCO");
        listDataHeader.add("FOLLOW");
        listDataHeader.add("REQUESTED");

        List<String> edmtDev = new ArrayList<>();
        edmtDev.add("This is Expandable ListView ");

        List<String> androidStudio = new ArrayList<>();
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");
        androidStudio.add("Expandable ListView ");
        androidStudio.add("Google Map");
        androidStudio.add("Chat Application");
        androidStudio.add("FireBase");

        List<String> xamarin = new ArrayList<>();
        xamarin.add("xamarin Expandable ListView ");
        xamarin.add("xamarin Google Map");
        xamarin.add("xamarin Chat Application");
        xamarin.add("xamarin FireBase");

        List<String> uwp = new ArrayList<>();
        uwp.add("uwp Expandable ListView ");
        uwp.add("uwp Google Map");
        uwp.add("uwp Chat Application");
        uwp.add("uwp FireBase");

        listHash.put(listDataHeader.get(0), edmtDev);
        listHash.put(listDataHeader.get(1), androidStudio);
        listHash.put(listDataHeader.get(2), xamarin);
        listHash.put(listDataHeader.get(3), uwp);

    }

}
